from .DNI import DNI
from .Efficient_BPTT import Efficient_BPTT
from .Future_BPTT import Future_BPTT
from .KeRNL import KeRNL
from .KF_RTRL import KF_RTRL
from .Learning_Algorithm import Learning_Algorithm
from .List_of_Gradients import List_of_Gradients
from .Only_Output_Weights import Only_Output_Weights
from .Random_Noise_Gradients import Random_Noise_Gradients
from .REINFORCE import REINFORCE
from .Reverse_KF_RTRL import Reverse_KF_RTRL
from .RFLO import RFLO
from .RTRL import RTRL
from .Stochastic_Algorithm import Stochastic_Algorithm
from .UORO import UORO